In [ ]:

import numpy as np

def gauss_jordan(x, y, verbose=0):
    m, n = x.shape
    augmented_mat = np.zeros(shape=(m, n + 1))
    augmented_mat[:m, :n] = x
    augmented_mat[:, m] = y
    np.set_printoptions(precision=2, suppress=True)
    if verbose > 0:
        print('# Matriks tambahan awal')
        print(augmented_mat)
    outer_loop = [[0, m - 1, 1], [m - 1, 0, -1]]
    for d in range(2):
        for i in range(outer_loop[d][0], outer_loop[d][1], outer_loop[d][2]):
            inner_loop = [[i + 1, m, 1], [i - 1, -1, -1]]
            for j in range(inner_loop[d][0], inner_loop[d][1], inner_loop[d][2]):
                k = (-1) * augmented_mat[j, i] / augmented_mat[i, i]
                temp_row = augmented_mat[i, :] * k
                if verbose > 1:
                    print('# Gunakan baris %2i untuk baris %2i' % (i + 1, j + 1))
                    print('k=%.2f' % k, '*', augmented_mat[i, :], '=', temp_row)
                augmented_mat[j, :] = augmented_mat[j, :] + temp_row
                if verbose > 1:
                    print(augmented_mat)
    for i in range(0, m):
        augmented_mat[i, :] = augmented_mat[i, :] / augmented_mat[i, i]
    if verbose > 0:
        print('# Normalisasi baris')
        print(augmented_mat)
    return augmented_mat[:, n]

if __name__ == "__main__":
    print("Contoh input yang benar:")
    print("2 1 1")
    print("1 1 -2")
    print("1 2 1")
    print("8 -2 2")
    print("\nMasukkan koefisien matriks (pisahkan angka dengan spasi):")
    matriks = []
    for i in range(3):
        row = list(map(int, input().split()))
        matriks.append(row)
    print("Masukkan sisi kanan matriks (pisahkan angka dengan spasi):")
    right_hand_side = list(map(int, input().split()))

    coefficients = np.array(matriks)
    right_hand_side = np.array(right_hand_side)

    verbose_input = input("Apakah Anda ingin menampilkan langkah-langkahnya? (y/n): ")
    verbose = 2 if verbose_input.lower() == "y" else 0

    hasil = gauss_jordan(coefficients, right_hand_side, verbose)
    print("Hasilnya adalah:", hasil)

Contoh input yang benar:
2 1 1
1 1 -2
1 2 1
8 -2 2

Masukkan koefisien matriks (pisahkan angka dengan spasi):
1 2 1
-1 1 -1
0 1 2
Masukkan sisi kanan matriks (pisahkan angka dengan spasi):
1 2 3
Apakah Anda ingin menampilkan langkah-langkahnya? (y/n): y
# Matriks tambahan awal
[[ 1.  2.  1.  1.]
 [-1.  1. -1.  2.]
 [ 0.  1.  2.  3.]]
# Gunakan baris  1 untuk baris  2
k=1.00 * [1. 2. 1. 1.] = [1. 2. 1. 1.]
[[1. 2. 1. 1.]
 [0. 3. 0. 3.]
 [0. 1. 2. 3.]]
# Gunakan baris  1 untuk baris  3
k=-0.00 * [1. 2. 1. 1.] = [-0. -0. -0. -0.]
[[1. 2. 1. 1.]
 [0. 3. 0. 3.]
 [0. 1. 2. 3.]]
# Gunakan baris  2 untuk baris  3
k=-0.33 * [0. 3. 0. 3.] = [-0. -1. -0. -1.]
[[1. 2. 1. 1.]
 [0. 3. 0. 3.]
 [0. 0. 2. 2.]]
# Gunakan baris  3 untuk baris  2
k=-0.00 * [0. 0. 2. 2.] = [-0. -0. -0. -0.]
[[1. 2. 1. 1.]
 [0. 3. 0. 3.]
 [0. 0. 2. 2.]]
# Gunakan baris  3 untuk baris  1
k=-0.50 * [0. 0. 2. 2.] = [-0. -0. -1. -1.]
[[1. 2. 0. 0.]
 [0. 3. 0. 3.]
 [0. 0. 2. 2.]]
# Gunakan baris  2 untuk baris  1
k=-0.67 * [0. 3